from .arithmeticspage import ArithmeticsPage
from .gauss_sum import Gauss_Sum
from .qequationpage import QEquationPage
from .rectanglesapage import RectanglesAPage
from .rectanglesppage import RectanglesPPage
from .squaresapage import SquaresAPage
from .squaresppage import SquaresPPage
from .lin_equation_page import Lin_EquationPage
from .pythagorean_theorem_page import Pythagorean_TheoremPage
