from .arithmeticspage import ArithmeticsPage
from .gauss_sum import Gauss_Sum
from .qequationpage import QEquationPage
from .rectanglesapage import RectanglesAPage
from .rectanglesppage import RectanglesPPage
from .squaresapage import SquaresAPage
from .squaresppage import SquaresPPage
from .lin_equation_page import Lin_EquationPage
from .pythagorean_theorem_page import Pythagorean_TheoremPage
from .sq_root_page import Sq_RootPage
from .cb_root_page import Cb_RootPage
from .power_number_page import Power_NumberPage
