from .sq_equation import square_equation
from .perimeter import perimeter_task
from .arithmetics import arithmetics
from .gauss_sum import gauss_sum
from .area import area_task
from .lin_equation import lin_equation
from .pythagorean_theorem import pythagorean_theorem
from .sq_root import sq_root
from .cb_root import cb_root
from .power_number import power_number
from .heron_formula import heron_formula
