# Move opened issues to Project "Tasks"

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add To GitHub Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.0.3
        with:
          project-url: https://github.com/TerraBoii/math_problem_generator_app/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
