# Move opened issues to Project "Tasks"

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add To GitHub Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.0.3
        with:
          project: Tasks
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
